on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow

    - shell: bash
      name: Create SSH deployment key
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: ./scripts/deploy.sh

    - name: Deployment to Umbler
      run: |
        git remote add umbler ssh://hml.zapisp.com.br@hml-zapisp-com-br.umbler.net:9922/~/git/hml-zapisp-com-br.git
        git fetch --unshallow origin
        git config --global user.email "deployumbler@github.com"
        git config --global user.name "deploy umbler"
        git commit --allow-empty -m "empty commity" --no-verify
        git push umbler master --no-verify --force
      env:
        CI: true
